# These are supported funding model platforms


# Apoie o Desafio XYZ

Estamos sempre buscando maneiras de melhorar e expandir o **Kids Wallet App**. Se você aprecia nosso trabalho e deseja apoiar nosso projeto, considere as seguintes opções de patrocínio:

## Formas de Apoio

### 1. Patrocínio em Criptomoedas
Você pode fazer doações usando Bitcoin. Aqui está nossa carteira:

**Carteira Bitcoin:**  
`15RAWooPeRazczEterHYdDDozxZksyQpDh`

### 2. Doações via PIX
Se você prefere apoiar via PIX, utilize o seguinte e-mail:

**PIX:**  
`adm.nuvem@protonmail.com`

### 3. Outros Métodos de Patrocínio
Se você gostaria de contribuir através de plataformas de patrocínio, considere as seguintes opções:

```yaml
github: hitice

